class FooError(Exception):
    pass

class BarError(Exception):
    pass
